config/routes.rb
RubyConsole::Application.routes.draw do

  resources :helloworlds

  match "/console" => "console#show", :via => :get
  match "/console" => "console#exec", :via => :post

end

app/models/helloworld.rb
class Helloworld < ActiveRecord::Base
  attr_accessible :sayhello
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController

  def show

  end

  def exec
    begin
      params[:output] = eval(params[:script])
    rescue Exception => e
      params[:output] = e.message
      p e.backtrace
    end

    respond_to do |format|
      format.html { render "show" }
      format.text { render :text => "#{params[:output]}\n" }
    end
  end

end

app/controllers/helloworlds_controller.rb
class HelloworldsController < ApplicationController
  # GET /helloworlds
  # GET /helloworlds.json
  def index
    @helloworlds = Helloworld.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @helloworlds }
    end
  end

  # GET /helloworlds/1
  # GET /helloworlds/1.json
  def show
    @helloworld = Helloworld.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @helloworld }
    end
  end

  # GET /helloworlds/new
  # GET /helloworlds/new.json
  def new
    @helloworld = Helloworld.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @helloworld }
    end
  end

  # GET /helloworlds/1/edit
  def edit
    @helloworld = Helloworld.find(params[:id])
  end

  # POST /helloworlds
  # POST /helloworlds.json
  def create
    @helloworld = Helloworld.new(params[:helloworld])

    respond_to do |format|
      if @helloworld.save
        format.html { redirect_to @helloworld, notice: 'Helloworld was successfully created.' }
        format.json { render json: @helloworld, status: :created, location: @helloworld }
      else
        format.html { render action: "new" }
        format.json { render json: @helloworld.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /helloworlds/1
  # PUT /helloworlds/1.json
  def update
    @helloworld = Helloworld.find(params[:id])

    respond_to do |format|
      if @helloworld.update_attributes(params[:helloworld])
        format.html { redirect_to @helloworld, notice: 'Helloworld was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @helloworld.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helloworlds/1
  # DELETE /helloworlds/1.json
  def destroy
    @helloworld = Helloworld.find(params[:id])
    @helloworld.destroy

    respond_to do |format|
      format.html { redirect_to helloworlds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helloworlds_helper.rb
module HelloworldsHelper
end

app/views/console/show.html.erb
<form action="" method="post">
  <textarea name="script" rows="20" cols="120"><%= params[:script] %></textarea>
  <input type="submit"/>
  <br/>
  Output: (@ <%= Time.now.strftime("%H:%M:%S") %>)
  <pre>
<%= params[:output] %>
  </pre>
</form>

app/views/helloworlds/_form.html.erb
<%= form_for(@helloworld) do |f| %>
  <% if @helloworld.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@helloworld.errors.count, "error") %> prohibited this helloworld from being saved:</h2>

      <ul>
      <% @helloworld.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sayhello %><br />
    <%= f.text_field :sayhello %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/helloworlds/edit.html.erb
<h1>Editing helloworld</h1>

<%= render 'form' %>

<%= link_to 'Show', @helloworld %> |
<%= link_to 'Back', helloworlds_path %>

app/views/helloworlds/index.html.erb
<h1>Listing helloworlds</h1>

<table>
  <tr>
    <th>Sayhello</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @helloworlds.each do |helloworld| %>
  <tr>
    <td><%= helloworld.sayhello %></td>
    <td><%= link_to 'Show', helloworld %></td>
    <td><%= link_to 'Edit', edit_helloworld_path(helloworld) %></td>
    <td><%= link_to 'Destroy', helloworld, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Helloworld', new_helloworld_path %>

app/views/helloworlds/new.html.erb
<h1>New helloworld</h1>

<%= render 'form' %>

<%= link_to 'Back', helloworlds_path %>

app/views/helloworlds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sayhello:</b>
  <%= @helloworld.sayhello %>
</p>


<%= link_to 'Edit', edit_helloworld_path(@helloworld) %> |
<%= link_to 'Back', helloworlds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyConsole</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>